# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('key', models.CharField(db_index=True, max_length=64)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('place', models.CharField(max_length=256)),
                ('book_start', models.DateTimeField(db_index=True)),
                ('book_end', models.DateTimeField(db_index=True)),
                ('total_tickets', models.IntegerField()),
                ('status', models.IntegerField()),
                ('pic_url', models.CharField(max_length=256)),
                ('remain_tickets', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, max_length=32)),
                ('unique_id', models.CharField(db_index=True, max_length=64)),
                ('status', models.IntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechat.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('student_id', models.CharField(db_index=True, max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('open_id', models.CharField(max_length=64, unique=True, db_index=True)),
                ('email', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ConfBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf_id', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('location', models.CharField(max_length=256)),
                ('image', models.CharField(max_length=256)),
                ('version', models.IntegerField()),
                ('private_type', models.IntegerField()),
                ('color', models.CharField(max_length=64)),
                ('sequence', models.CharField(max_length=64)),
                ('status', models.IntegerField()),
                ('preview_code', models.CharField(max_length=128)),
                ('zipcode', models.CharField(max_length=8)),
                ('decs', models.TextField()),
                ('poster', models.CharField(max_length=256)),
                ('org', models.CharField(max_length=128)),
                ('website', models.CharField(max_length=256)),
                ('reg_url', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=16)),
                ('fax', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=64)),
                ('wei_bo', models.CharField(max_length=64)),
                ('wei_xin', models.CharField(max_length=64)),
                ('qq', models.CharField(max_length=64)),
                ('longitude', models.CharField(max_length=64)),
                ('latitude', models.CharField(max_length=64)),
                ('timezone', models.CharField(max_length=16)),
            ],
        )
    ]
