# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-07 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='email',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
