# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-19 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='my_conf',
            field=models.ManyToManyField(to='wechat.ConfBasic'),
        ),
    ]
