# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-07 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0002_auto_20161207_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='student_id',
        ),
    ]
