# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-07 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0003_remove_user_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='watching_page',
            field=models.IntegerField(default=0),
        ),
    ]
