# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-30 08:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0003_confbasic_money'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confbasic',
            old_name='money',
            new_name='price',
        ),
    ]
