# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-07 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0005_auto_20161207_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='watching_page',
        ),
    ]
