# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-07 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0006_remove_userlogin_watching_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='watching_page',
            field=models.IntegerField(default=1),
        ),
    ]
